### ISSUE TITLE
Issue where carbon-list comes back empty

### ISSUE THREAD

**Issue by wingZero21** [jssjr/carbonate#29]
Hi,

I have added the conf file as suggested with a user that has keys to the servers on the cluster, however when running the commands (IE carbon-list) it just comes back blank.

Any ideas why this might be. The only command I can see to run is if I run it on the local graphite server and tell it to look at the directory specifically.

Any ideas why when trying to run it again the cluster it just seems to bring back nothing not even an error.

**Comment by jssjr** [comment]
@wingZero21 - I hope you got things working! I'm going to close this issue, but feel free to make a comment to the contrary and I'll reopen it.
