### ISSUE TITLE
how does carbonate interact with multiple caches ?

### ISSUE THREAD

**Issue by rgevaert** [jssjr/carbonate#38]
Hi,

I'm trying to figure out how carbonate works with multiple carbon caches running on the same host.  It clearly has an impact when using e.g. carbon-lookup.

Am I correct one actually has to use the same DESTINATION in carbonate.conf as in carbon.conf?

E.g. with this in the config:
```shell
DESTINATIONS = graphite1.mynode.com:2104:1, graphite1.mynode.com:2204:2, graphite1.mynode.com:2304:3, graphite2.mynode.com:2104:1, graphite2.mynode.com:2204:2, graphite2.mynode.com:2304:3, graphite3.mynode.com:2104:1, graphite3.mynode.com:2204:2, graphite3.mynode.com:2304:3, graphite4.mynode.com:2104:1, graphite4.mynode.com:2204:2, graphite4.mynode.com:2304:3
```

On the other hand this doesn't seem to be right:

```shell
root@graphite1:~/scripts# carbon-hosts -c /etc/carbon/carbonate.conf 
graphite1.mynode.com
graphite1.mynode.com
graphite1.mynode.com
graphite2.mynode.com
graphite2.mynode.com
graphite2.mynode.com
graphite3.mynode.com
graphite3.mynode.com
graphite3.mynode.com
graphite4.mynode.com
graphite4.mynode.com
graphite4.mynode.com
```

**Comment by jssjr** [comment]
The `carbon-hosts` tool will just list the hosts. However, the `DESTINATIONS` directive for your cluster should match what carbon itself uses. The hashing algorithm takes into account [the host and instance name and ignores the port](https://github.com/graphite-project/carbon/blob/master/lib/carbon/routers.py#L49-L54) and carbonate does the same thing.

For example, given carbonate.conf:

```
[test]
DESTINATIONS = 192.168.251.40:2004:aggregator1, 192.168.254.40:2104:aggregator2, 192.168.254.40:2204:aggregator3, 192.168.254.40:2304:aggregator4, 192.168.254.40:2404:aggregator5
REPLICATION_FACTOR = 2
```

Then,

```
% bin/carbon-hosts -c conf/carbonate.conf -C test
192.168.251.40
192.168.254.40
192.168.254.40
192.168.254.40
192.168.254.40
```

and,

```
% bin/carbon-lookup -c conf/carbonate.conf -C test foo.bar
192.168.254.40:2404:aggregator5
192.168.254.40:2104:aggregator2
```

Make sense?
